on:
  pull_request:
    branches:
      - main
      - master
  push:
    branches:
      - main
      - master
      - develop

name: Build & Release

jobs:
  build:
    name: Build & Release
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      
      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17.0.9+8'
          
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          architecture: x64
      
      # Find flutter_html_to_pdf package path
      - name: Find flutter_html_to_pdf package path
        id: find-package-path
        run: echo "$(find . -type d -name 'flutter_html_to_pdf')"
        shell: /bin/zsh -e

      # Update Kotlin Gradle plugin version
      - name: Update Kotlin Gradle plugin version
        run: |
          path="${{ steps.find-package-path.outputs.path }}"
          if [[ -z "$path" ]]; then
            echo "flutter_html_to_pdf package path not found"
            exit 1
          else
            cd $path
            sed -i '' 's/org.jetbrains.kotlin:kotlin-gradle-plugin:1.3.50/org.jetbrains.kotlin:kotlin-gradle-plugin:1.5.31/' build.gradle
          fi
        shell: /bin/zsh -e
        
      # Proceed with the rest of the build process
      - run: flutter build apk --release --split-per-abi
        shell: /bin/zsh -e
        
      - run: |
          flutter build ios --no-codesign
          cd build/ios/iphoneos
          mkdir Payload
          cd Payload
          ln -s ../Runner.app
          cd ..
          zip -r app.ipa Payload
        shell: /bin/zsh -e

      - name: Push to Releases
        uses: ncipollo/release-action@v1
        with:
          artifacts: "build/app/outputs/apk/release/*,build/ios/iphoneos/app.ipa"
          tag: v1.0.${{ github.run_number }}
          token: ${{ secrets.TOKEN }}
